# Generated by Django 5.1.6 on 2025-04-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userotherdetails_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotherdetails',
            name='type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
    ]
