# Generated by Django 5.1.6 on 2025-02-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
    ]
