# Generated by Django 5.1.6 on 2025-04-26 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_preference_song_user_mood_playlist_preference_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.preference'),
        ),
    ]
