# Generated by Django 5.1.6 on 2025-04-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
    ]
